/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class dsaActor extends Actor {
  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  prepareBaseData() {
    super.prepareBaseData();

    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't 
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    super.prepareDerivedData();

    const featureSummary = this._prepareFeatureEffects();
    this.featureSummary = featureSummary;
  }

  /**
   * 
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic 
   * approach is useful when you have actors & items that share a parent Document, 
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...this.system.getRollData?.() ?? null };
  }

  /**
   * Convert the actor document to a plain object.
   * 
   * The built in `toObject()` method will ignore derived data when using Data Models.
   * This additional method will instead use the spread operator to return a simplified
   * version of the data.
   * 
   * @returns {object} Plain object either via deepClone or the spread operator.
   */
  toPlainObject() {
    const result = {...this};

    // Simplify system data.
    result.system = this.system.toPlainObject();

    // Add items.
    result.items = this.items?.size > 0 ? this.items.contents : [];

    // Add effects.
    result.effects = this.effects?.size > 0 ? this.effects.contents : [];

    return result;
  }

  _prepareFeatureEffects() {
    const summary = {
      abilities: Object.keys(CONFIG.DSA.abilities ?? {}).reduce((obj, key) => {
        obj[key] = 0;
        return obj;
      }, {}),
      resources: {
        lebensenergie: { value: 0, max: 0 },
        power: { value: 0, max: 0 },
      },
      derivedRules: [],
    };

    for (const item of this.items.contents) {
      if (item.type !== 'feature') continue;

      for (const effect of item.system.effects ?? []) {
        this._applyFeatureEffect(item, effect, summary);
      }
    }

    return summary;
  }

  _applyFeatureEffect(item, effect, summary) {
    const amount = this._getFeatureEffectAmount(item, effect);
    const note = effect.note?.trim();
    const source = item.name;

    if (effect.type === 'modifyResource') {
      if (effect.targetType === 'ability' && this.system.abilities?.[effect.target]) {
        this.system.abilities[effect.target].value += amount;
        summary.abilities[effect.target] += amount;
        return;
      }

      const resource = this._resolveFeatureResource(effect.target);
      if (resource && this.system[resource]) {
        const mode = (effect.mode || 'max').toLowerCase();

        if (mode === 'value' || mode === 'both') {
          this.system[resource].value += amount;
          summary.resources[resource].value += amount;
        }
        if (mode === 'max' || mode === 'both') {
          this.system[resource].max += amount;
          summary.resources[resource].max += amount;
        }
        return;
      }
    }

    summary.derivedRules.push({
      source,
      type: effect.type,
      typeLabel: game.i18n.localize(CONFIG.DSA.featureEffectTypes?.[effect.type] ?? effect.type),
      targetType: effect.targetType,
      target: effect.target,
      mode: effect.mode,
      value: amount,
      max: effect.max,
      note,
    });
  }

  _getFeatureEffectAmount(item, effect) {
    const base = Number(effect.value) || 0;
    const level = item.system.levels?.current ?? 1;

    if (effect.mode === 'perLevel') {
      return base * level;
    }

    return base;
  }

  _resolveFeatureResource(target) {
    const normalized = String(target ?? '').trim().toLowerCase();

    if (['lebensenergie', 'le', 'lifepoints', 'life'].includes(normalized)) return 'lebensenergie';
    if (['power', 'astralpunkte', 'astralenergie', 'asp'].includes(normalized)) return 'power';

    return null;
  }

}
